---
deployment:
 tasks:
 - export DEPLOYPATH=/home/blendeei/public_html/
 - /bin/cp -R css $DEPLOYPATH
 - /bin/cp -R js $DEPLOYPATH
 - /bin/cp -R Photographers $DEPLOYPATH
 - /bin/cp index.html $DEPLOYPATH
 - /bin/cp README.md $DEPLOYPATH